declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';
  
  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: number | string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
  }
  
  export type Icon = FC<IconProps>;
  
  // Export all commonly used icons
  export const CheckCircle: Icon;
  export const CheckCircle2: Icon;
  export const XCircle: Icon;
  export const Users: Icon;
  export const TrendingUp: Icon;
  export const TrendingDown: Icon;
  export const Target: Icon;
  export const Zap: Icon;
  export const Award: Icon;
  export const Activity: Icon;
  export const Calendar: Icon;
  export const Flame: Icon;
  export const Heart: Icon;
  export const Brain: Icon;
  export const Dumbbell: Icon;
  export const Moon: Icon;
  export const Apple: Icon;
  export const AlertTriangle: Icon;
  export const AlertCircle: Icon;
  export const Info: Icon;
  export const Clock: Icon;
  export const Baby: Icon;
  export const Utensils: Icon;
  export const Shield: Icon;
  export const Smile: Icon;
  export const Book: Icon;
  export const Sparkles: Icon;
  export const Timer: Icon;
  export const FileText: Icon;
  export const MapPin: Icon;
  export const Phone: Icon;
  export const Mail: Icon;
  export const Globe: Icon;
  export const Star: Icon;
  export const ChevronDown: Icon;
  export const ChevronRight: Icon;
  export const ChevronLeft: Icon;
  export const ChevronUp: Icon;
  export const Search: Icon;
  export const Menu: Icon;
  export const X: Icon;
  export const Tag: Icon;
  export const ArrowLeft: Icon;
  export const ArrowRight: Icon;
  export const ArrowUp: Icon;
  export const ArrowDown: Icon;
  export const Share2: Icon;
  export const ExternalLink: Icon;
  export const Loader: Icon;
  export const MessageCircle: Icon;
  export const ThumbsUp: Icon;
  export const Eye: Icon;
  export const Send: Icon;
  export const Euro: Icon;
  export const DollarSign: Icon;
  export const Lightbulb: Icon;
  export const BarChart3: Icon;
  export const BarChart: Icon;
  export const PieChart: Icon;
  export const LineChart: Icon;
  export const Plus: Icon;
  export const Minus: Icon;
  export const Check: Icon;
  export const Home: Icon;
  export const Settings: Icon;
  export const User: Icon;
  export const LogOut: Icon;
  export const LogIn: Icon;
  export const Lock: Icon;
  export const Unlock: Icon;
  export const Camera: Icon;
  export const Image: Icon;
  export const Video: Icon;
  export const Music: Icon;
  export const Download: Icon;
  export const Upload: Icon;
  export const Trash: Icon;
  export const Edit: Icon;
  export const Copy: Icon;
  export const Save: Icon;
  export const Filter: Icon;
  export const SortAsc: Icon;
  export const SortDesc: Icon;
  export const Pill: Icon;
  export const Stethoscope: Icon;
  export const Thermometer: Icon;
  export const Activity2: Icon;
  export const BookOpen: Icon;
  export const Battery: Icon;
  export const Bone: Icon;
  export const Calculator: Icon;
  export const Camera: Icon;
  export const ChefHat: Icon;
  export const Clipboard: Icon;
  export const ClipboardList: Icon;
  export const Coffee: Icon;
  export const CreditCard: Icon;
  export const Droplet: Icon;
  export const FileCheck: Icon;
  export const FileSearch: Icon;
  export const GraduationCap: Icon;
  export const Leaf: Icon;
  export const MessageSquare: Icon;
  export const PiggyBank: Icon;
  export const Scale: Icon;
  export const ShieldAlert: Icon;
  export const Trophy: Icon;
  export const Wifi: Icon;
  export const HelpCircle: Icon;
  export const Crown: Icon;
  export const Building2: Icon;
  export const Monitor: Icon;
  
  // Fallback for any other icons
  const icons: Record<string, Icon>;
  export default icons;
}
